admin:
  build: ./nprima-admin/
  expose:
    - "80"
api:
  build: ./nprima-engine/
  dockerfile: rest.Dockerfile
  expose: 
    - "80"
spiderman:
  build: ./aio-spider/
  expose:
    - "80"
lb:
  build: ./ops/nginx/
  links:
    - admin
    - spiderman
    - api
  ports:
    - "80:80"
