admin:
  build: ./nprima_admin/
  expose:
    - "80"
spiderman:
  build: ./aio_spider/
  expose:
    - "80"
  ports:
    - "8888:80"
lb:
  build: ./ops/nginx/
  links:
    - admin
    - spiderman
  ports:
    - "80:80"
